// Git installs update in Terminal; release installs from the menu (#214).

import Foundation

enum InstallKindTests {
    static let release = URL(fileURLWithPath: "/Users/u/.local/share/quern", isDirectory: true)

    private static func kind(resolved: String?, files: [String: String] = [:],
                             existing: Set<String> = []) -> InstallKind {
        InstallKind.of(resolved: resolved, releaseRoot: release,
                       readFile: { files[$0] },
                       exists: { existing.contains($0) })
    }

    static let wrapper = "/Users/u/.local/bin/quern"

    static func wrapperText(root: String) -> String {
        "#!/usr/bin/env bash\n# Quern wrapper — auto-generated by ./quern setup\n"
            + "# Points to: \(root)\nexec \"\(root)/.venv/bin/python\" -m server \"$@\"\n"
    }

    static func all() {
        Harness.test("a wrapper pointing at a clone is a git install") {
            let got = kind(resolved: wrapper,
                           files: [wrapper: wrapperText(root: "/Users/u/Dev/quern")],
                           existing: ["/Users/u/Dev/quern/.git"])
            Harness.expect(got, .git(URL(fileURLWithPath: "/Users/u/Dev/quern", isDirectory: true)),
                           "kind")
        }

        Harness.test("a worktree's .git file still counts") {
            // `exists`, not a directory test: a worktree's .git is a file.
            let got = kind(resolved: wrapper,
                           files: [wrapper: wrapperText(root: "/w/tree")],
                           existing: ["/w/tree/.git"])
            Harness.expect(got.isGit, true, "worktree is git")
        }

        Harness.test("a wrapper pointing at the release install is a release") {
            let got = kind(resolved: wrapper,
                           files: [wrapper: wrapperText(root: release.path)])
            Harness.expect(got, .release(release), "kind")
        }

        Harness.test("the release venv binary is a release without reading a header") {
            let bin = release.appendingPathComponent(".venv/bin/quern-debug-server").path
            Harness.expect(kind(resolved: bin), .release(release), "kind")
        }

        Harness.test("a release root that happens to be a checkout is still git") {
            let bin = release.appendingPathComponent(".venv/bin/quern-debug-server").path
            let got = kind(resolved: bin, existing: [release.appendingPathComponent(".git").path])
            Harness.expect(got.isGit, true, "git wins over location")
        }

        Harness.test("nothing resolved, or a quern that names no root, is unknown") {
            Harness.expect(kind(resolved: nil), .unknown, "nothing")
            Harness.expect(kind(resolved: "/opt/homebrew/bin/quern",
                                files: ["/opt/homebrew/bin/quern": "#!/bin/sh\n"]),
                           .unknown, "no header")
        }

        Harness.test("git installs are offered Terminal, releases a restart") {
            // `node:` is passed explicitly everywhere: its default reads the
            // real machine, and a test that did that would be a report about
            // whoever ran it.
            let git = InstallKind.git(URL(fileURLWithPath: "/c", isDirectory: true))
            Harness.expect(UpdateMenuItem.forStaged(install: git,
                                                    node: .visible),
                           .updateInTerminal("Update in Terminal…", .gitInstall), "git")
            Harness.expect(UpdateMenuItem.forStaged(install: .release(release), node: .visible),
                           .restartToUpdate("Restart to Update"), "release")
            // Unknown keeps today's behaviour rather than guessing git.
            Harness.expect(UpdateMenuItem.forStaged(install: .unknown,
                                                    node: .visible),
                           .restartToUpdate("Restart to Update"), "unknown")
        }

        Harness.test("a release install whose node is managed goes to Terminal, naming the manager") {
            // The #339 case: node exists and works in every shell, and this
            // launch cannot see it, so the update fails naming Node.
            Harness.expect(UpdateMenuItem.forStaged(install: .release(release),
                                                    node: .managedElsewhere("fnm")),
                           .updateInTerminal("Update in Terminal…",
                                             .nodeManagedElsewhere("fnm")), "fnm")
            Harness.expect(TerminalReason.nodeManagedElsewhere("fnm").menuTitle,
                           "Why Terminal? (Node is managed by fnm)", "says which one")
        }

        Harness.test("no version is promised: the update installs the latest (#352)") {
            // The cached latest_version is refreshed at most once a day, and
            // the update installs whatever is newest -- so a number here could
            // be older than what the click installs.
            let git = InstallKind.git(URL(fileURLWithPath: "/c", isDirectory: true))
            for item in [UpdateMenuItem.forStaged(install: .release(release), node: .visible),
                         UpdateMenuItem.forStaged(install: git, node: .visible),
                         UpdateMenuItem.forStaged(install: .release(release),
                                                  node: .managedElsewhere("fnm"))] {
                let title: String
                switch item {
                case .restartToUpdate(let t): title = t
                case .updateInTerminal(let t, _): title = t
                }
                Harness.expect(title.range(of: #"v\d"#, options: .regularExpression) == nil
                               && !title.contains("—"), "no version in \(title)")
            }
            Harness.expect(UpdateMenuItem.tooltip(failed: false, updateAvailable: true,
                                                  running: true),
                           "Quern — update available", "tooltip")
            Harness.expect(UpdateMenuItem.tooltip(failed: true, updateAvailable: true,
                                                  running: false),
                           "Quern could not start — open the menu", "a failure comes first")
            Harness.expect(UpdateMenuItem.tooltip(failed: false, updateAvailable: false,
                                                  running: false), "Quern is stopped", "stopped")
            Harness.expect(UpdateMenuItem.tooltip(failed: false, updateAvailable: false,
                                                  running: true), "Quern is running", "running")
            Harness.expect(UpdateMenuItem.tooltip(failed: false, updateAvailable: true,
                                                  running: false),
                           "Quern — update available", "an update wins over stopped")
            Harness.expect(UpdateMenuItem.settingsLine(updateAvailable: true), "Update available",
                           "settings: no version, and no Up to date while one waits")
            Harness.expect(UpdateMenuItem.settingsLine(updateAvailable: false), "Up to date",
                           "settings: nothing waiting")
        }

        Harness.test("a genuinely absent node is not sent to Terminal") {
            // Terminal would not help: there is no node there either. Routing it
            // would move the same failure somewhere the user has to type.
            Harness.expect(UpdateMenuItem.forStaged(install: .release(release), node: .absent),
                           .restartToUpdate("Restart to Update"), "absent stays put")
            Harness.expect(NodeVisibility.absent.needsTerminal, false, "absent")
            Harness.expect(NodeVisibility.visible.needsTerminal, false, "visible")
            Harness.expect(NodeVisibility.managedElsewhere("nvm").needsTerminal, true, "managed")
        }

        Harness.test("a git install reports the git reason even when node is also hidden") {
            // Both apply. Git is the property of the install and true on every
            // machine; the node one is a property of this launch.
            let git = InstallKind.git(URL(fileURLWithPath: "/c", isDirectory: true))
            Harness.expect(UpdateMenuItem.forStaged(install: git,
                                                    node: .managedElsewhere("fnm")),
                           .updateInTerminal("Update in Terminal…", .gitInstall), "git wins")
        }

        Harness.test("node is looked for on the same PATH the child will get") {
            let home = "/home/u"
            // Present on the app's own search path.
            Harness.expect(NodeVisibility.check(home: home, searchPath: ["/opt/homebrew/bin"],
                                                isExecutable: { $0 == "/opt/homebrew/bin/node" },
                                                exists: { _ in false }),
                           .visible, "found")
            // Absent, but fnm's per-shell directory is on disk -- the real case.
            Harness.expect(NodeVisibility.check(home: home, searchPath: ["/usr/bin"],
                                                isExecutable: { _ in false },
                                                exists: { $0 == "\(home)/.local/state/fnm_multishells" }),
                           .managedElsewhere("fnm"), "fnm multishells")
            Harness.expect(NodeVisibility.check(home: home, searchPath: ["/usr/bin"],
                                                isExecutable: { _ in false },
                                                exists: { $0 == "\(home)/.nvm" }),
                           .managedElsewhere("nvm"), "nvm")
            // Nothing anywhere.
            Harness.expect(NodeVisibility.check(home: home, searchPath: ["/usr/bin"],
                                                isExecutable: { _ in false },
                                                exists: { _ in false }),
                           .absent, "nothing")
        }

        Harness.test("the Terminal script runs the wrapper it was given, quoted") {
            let script = TerminalUpdate.script(quern: "/Users/o'neil/.local/bin/quern")
            Harness.expect(script.hasPrefix("#!/bin/sh\n"), "has a shebang")
            Harness.expect(script.contains("'/Users/o'\\''neil/.local/bin/quern' update"),
                           "quoted path runs update: \(script)")
        }

        Harness.test("the window stays open once the update is done") {
            // Terminal closes a window whose shell exits cleanly, which hid a
            // successful update's output. The script's last act hands the
            // window to a shell instead of exiting.
            let lines = TerminalUpdate.script(quern: "/q").split(separator: "\n")
            Harness.expect(lines.last.map(String.init), "exec \"${SHELL:-/bin/zsh}\" -l",
                           "last command")
            Harness.expect(!lines.contains { $0.hasPrefix("exit") }, "no exit before the shell")
        }

        Harness.test("Settings names the install") {
            let model = SettingsModel()
            model.readInstall = { .git(URL(fileURLWithPath: "/Users/u/Dev/quern", isDirectory: true)) }
            let row = model.serverRows(now: Date()).first { $0.0 == "Install" }?.1
            Harness.expect(row?.hasPrefix("Git checkout — ") == true, "row: \(row ?? "missing")")
        }
    }
}
