// Git installs update in Terminal; release installs from the menu (#214).

import Foundation

enum InstallKindTests {
    static let release = URL(fileURLWithPath: "/Users/u/.local/share/quern", isDirectory: true)

    private static func kind(resolved: String?, files: [String: String] = [:],
                             existing: Set<String> = []) -> InstallKind {
        InstallKind.of(resolved: resolved, releaseRoot: release,
                       readFile: { files[$0] },
                       exists: { existing.contains($0) })
    }

    static let wrapper = "/Users/u/.local/bin/quern"

    static func wrapperText(root: String) -> String {
        "#!/usr/bin/env bash\n# Quern wrapper — auto-generated by ./quern setup\n"
            + "# Points to: \(root)\nexec \"\(root)/.venv/bin/python\" -m server \"$@\"\n"
    }

    static func all() {
        Harness.test("a wrapper pointing at a clone is a git install") {
            let got = kind(resolved: wrapper,
                           files: [wrapper: wrapperText(root: "/Users/u/Dev/quern")],
                           existing: ["/Users/u/Dev/quern/.git"])
            Harness.expect(got, .git(URL(fileURLWithPath: "/Users/u/Dev/quern", isDirectory: true)),
                           "kind")
        }

        Harness.test("a worktree's .git file still counts") {
            // `exists`, not a directory test: a worktree's .git is a file.
            let got = kind(resolved: wrapper,
                           files: [wrapper: wrapperText(root: "/w/tree")],
                           existing: ["/w/tree/.git"])
            Harness.expect(got.isGit, true, "worktree is git")
        }

        Harness.test("a wrapper pointing at the release install is a release") {
            let got = kind(resolved: wrapper,
                           files: [wrapper: wrapperText(root: release.path)])
            Harness.expect(got, .release(release), "kind")
        }

        Harness.test("the release venv binary is a release without reading a header") {
            let bin = release.appendingPathComponent(".venv/bin/quern-debug-server").path
            Harness.expect(kind(resolved: bin), .release(release), "kind")
        }

        Harness.test("a release root that happens to be a checkout is still git") {
            let bin = release.appendingPathComponent(".venv/bin/quern-debug-server").path
            let got = kind(resolved: bin, existing: [release.appendingPathComponent(".git").path])
            Harness.expect(got.isGit, true, "git wins over location")
        }

        Harness.test("nothing resolved, or a quern that names no root, is unknown") {
            Harness.expect(kind(resolved: nil), .unknown, "nothing")
            Harness.expect(kind(resolved: "/opt/homebrew/bin/quern",
                                files: ["/opt/homebrew/bin/quern": "#!/bin/sh\n"]),
                           .unknown, "no header")
        }

        Harness.test("git installs are offered Terminal, releases a restart") {
            let git = InstallKind.git(URL(fileURLWithPath: "/c", isDirectory: true))
            Harness.expect(UpdateMenuItem.forStaged(latestVersion: "0.18.5", install: git),
                           .updateInTerminal("Update in Terminal… — v0.18.5"), "git")
            Harness.expect(UpdateMenuItem.forStaged(latestVersion: "0.18.5", install: .release(release)),
                           .restartToUpdate("Restart to Update — v0.18.5"), "release")
            // Unknown keeps today's behaviour rather than guessing git.
            Harness.expect(UpdateMenuItem.forStaged(latestVersion: nil, install: .unknown),
                           .restartToUpdate("Restart to Update"), "unknown")
        }

        Harness.test("the Terminal script runs the wrapper it was given, quoted") {
            let script = TerminalUpdate.script(quern: "/Users/o'neil/.local/bin/quern")
            Harness.expect(script.hasPrefix("#!/bin/sh\n"), "has a shebang")
            Harness.expect(script.contains("'/Users/o'\\''neil/.local/bin/quern' update"),
                           "quoted path runs update: \(script)")
        }

        Harness.test("Settings names the install") {
            let model = SettingsModel()
            model.readInstall = { .git(URL(fileURLWithPath: "/Users/u/Dev/quern", isDirectory: true)) }
            let row = model.serverRows(now: Date()).first { $0.0 == "Install" }?.1
            Harness.expect(row?.hasPrefix("Git checkout — ") == true, "row: \(row ?? "missing")")
        }
    }
}
