"""How messages spell the command they are telling you to run.

`./quern doctor` has not been necessary since `quern setup` began writing
`~/.local/bin/quern`, and for a tarball install it is actively wrong -- the
reader is not necessarily standing in the extracted directory.

But it cannot simply be replaced. The same strings are printed in two different
situations. `quern doctor` runs after a successful install, where `./quern` is
awkward; most of `setup.py`'s checks run *before* `install_wrapper_script()`,
where `quern` names a command the reader does not have yet. A static choice is
wrong in one of the two, so the answer is decided when the message is built.

See #192.
"""

from __future__ import annotations

import ast
import os
from pathlib import Path

from server.config import quern_cmd

SERVER = Path(__file__).resolve().parent.parent / "server"

#: The two literals that are legitimately `./quern`, pinned to their exact text.
#:
#: Exempting whole *files* was the first attempt and it was wrong: it allow-
#: listed `setup.py`, which has more message sites than anything else and is
#: where new check details get added. A hardcoded `./quern doctor` inserted
#: anywhere in it passed. Matching the literal instead means the exemption
#: covers the one string it was granted for and nothing else in the file.
#: Exactly this string, and nothing else, is allowed as a whole literal.
EXEMPT_EXACT = {"./quern"}  # the value `quern_cmd` itself returns

#: A literal containing this is allowed. It is the header comment baked into
#: the *generated* wrapper, naming the command that produced the file --
#: provenance, not an instruction. Matched as a fragment because it lives
#: inside an f-string template, so the AST sees it in pieces.
EXEMPT_CONTAINING = "Quern wrapper — auto-generated by ./quern setup"


class TestTheCommandIsResolvedNotAssumed:
    """Three situations, three answers. Only one tolerates a guess."""

    def test_it_is_bare_when_the_wrapper_is_on_path(self, monkeypatch):
        monkeypatch.setattr(
            "server.config.shutil.which", lambda _n: "/home/u/.local/bin/quern",
        )
        assert quern_cmd() == "quern"

    def test_it_is_relative_only_when_the_reader_is_standing_in_the_project(
        self, monkeypatch,
    ):
        monkeypatch.setattr("server.config.shutil.which", lambda _n: None)
        root = Path(__file__).resolve().parent.parent
        monkeypatch.chdir(root)
        assert quern_cmd() == "./quern"

    def test_it_is_absolute_when_the_reader_is_somewhere_else(
        self, monkeypatch, tmp_path,
    ):
        """The case that makes this more than cosmetic.

        An install script drops quern in `~/.local/share/quern` and leaves the
        terminal wherever it was. Telling that user to run `./quern setup`
        points at a file that is not in their directory -- and they are the
        least likely person to work out why.
        """
        monkeypatch.setattr("server.config.shutil.which", lambda _n: None)
        monkeypatch.chdir(tmp_path)
        answer = quern_cmd()
        assert answer.startswith("/"), f"{answer!r} is not runnable from here"
        # `exists()` and `endswith("/quern")` are both satisfied by the project
        # *directory* whenever that directory is itself named `quern` -- which
        # is a git clone, the documented tarball path `~/.local/share/quern`,
        # and CI's checkout. Assert it is a runnable file.
        assert Path(answer).is_file(), f"{answer!r} is not a file"
        assert os.access(answer, os.X_OK), f"{answer!r} is not executable"

    def test_a_missing_wrapper_does_not_name_a_file_that_is_not_there(
        self, monkeypatch, tmp_path,
    ):
        """Reachable when `server/` is importable without the repo root -- a
        non-editable `pip install`, which pyproject supports via a console
        script. Naming a path that does not exist is worse than naming one that
        might be on PATH."""
        monkeypatch.setattr("server.config.shutil.which", lambda _n: None)
        monkeypatch.setattr("server.config.__file__", str(tmp_path / "server" / "config.py"))
        monkeypatch.chdir(tmp_path)
        answer = quern_cmd()
        assert answer == "quern", f"named {answer!r}, which is not there"

    def test_a_path_with_spaces_stays_copy_pasteable(self, monkeypatch, tmp_path):
        """Before this change the token was always `./quern`, which cannot
        contain a space. Emitting a path introduces the exposure."""
        import shlex

        root = tmp_path / "my apps" / "quern dir"
        (root / "server").mkdir(parents=True)
        (root / "quern").write_text("#!/bin/sh\n")
        (root / "quern").chmod(0o755)
        monkeypatch.setattr("server.config.shutil.which", lambda _n: None)
        monkeypatch.setattr("server.config.__file__", str(root / "server" / "config.py"))
        monkeypatch.chdir(tmp_path)
        answer = quern_cmd()
        assert shlex.split(answer) == [str(root / "quern")], (
            f"{answer!r} does not survive being pasted into a shell"
        )

    def test_it_asks_path_rather_than_the_wrapper_file(self, monkeypatch):
        """`which`, not `WRAPPER_PATH.exists()`.

        The wrapper can exist while `~/.local/bin` is absent from PATH, which
        CONTRIBUTING documents as a live failure -- zsh caches its first
        resolution, so `type -a` and what actually runs can disagree.
        """
        asked = []
        monkeypatch.setattr(
            "server.config.shutil.which", lambda n: asked.append(n) or None,
        )
        quern_cmd()
        assert asked == ["quern"]

    def test_the_answer_is_not_frozen_for_the_process(self, monkeypatch, tmp_path):
        """It depends on PATH, on the wrapper existing, and on the directory --
        and all three move. Setup installs the wrapper partway through its own
        run; uninstall removes it; anything may chdir. A cached answer would
        need invalidating at each, which is three chances to miss one.
        """
        on_path = {"yes": False}
        monkeypatch.setattr(
            "server.config.shutil.which",
            lambda _n: "/home/u/.local/bin/quern" if on_path["yes"] else None,
        )
        monkeypatch.chdir(tmp_path)
        before = quern_cmd()
        on_path["yes"] = True
        assert before != quern_cmd(), (
            "the wrapper appeared mid-process and the advice did not change"
        )


class TestNoMessageHardcodesTheRelativeForm:
    """Without this, it reaccumulates: every new check detail is a fresh chance
    to type `./quern`, and nothing would notice."""

    def _offenders(self, root: Path | None = None) -> list[str]:
        """Message literals containing a hardcoded `./quern`.

        Takes a root so the test below can point it at a decoy tree. A guard
        that is only ever run against the real source cannot distinguish
        "found nothing" from "looked nowhere".
        """
        root = root or SERVER
        found = []
        for path in sorted(root.rglob("*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"))
            # Docstrings are prose about the wrapper script, not advice to run
            # it; rewriting them would make them inaccurate rather than modern.
            docstrings = set()
            for node in ast.walk(tree):
                if isinstance(node, (ast.Module, ast.ClassDef,
                                     ast.FunctionDef, ast.AsyncFunctionDef)):
                    body = node.body
                    if body and isinstance(body[0], ast.Expr) and \
                            isinstance(body[0].value, ast.Constant) and \
                            isinstance(body[0].value.value, str):
                        docstrings.add(id(body[0].value))
            for node in ast.walk(tree):
                if not (isinstance(node, ast.Constant)
                        and isinstance(node.value, str)):
                    continue
                if "./quern" not in node.value or id(node) in docstrings:
                    continue
                if node.value in EXEMPT_EXACT or EXEMPT_CONTAINING in node.value:
                    continue
                found.append(f"{path.relative_to(root)}:{node.lineno}")
        return found

    def test_no_string_literal_says_dot_slash_quern(self):
        offenders = self._offenders()
        assert not offenders, (
            "these build a message with a hardcoded './quern'; use "
            f"quern_cmd() so it is right in both contexts: {offenders}"
        )

    def test_the_guard_finds_one_when_there_is_one(self, tmp_path):
        """Run the real scanner over a planted tree.

        The first version re-implemented the AST walk inline, so it proved the
        `ast` module works and nothing about the guard: making `_offenders`
        never append, or pointing it at `*.pyx`, or searching for a string that
        appears nowhere, all passed it.
        """
        (tmp_path / "decoy.py").write_text('msg = "run ./quern doctor"\n')
        assert self._offenders(tmp_path) == ["decoy.py:1"]

    def test_the_guard_ignores_prose_and_the_exempt_literals(self, tmp_path):
        (tmp_path / "prose.py").write_text('"""How ./quern re-execs."""\n')
        (tmp_path / "value.py").write_text('x = "./quern"\n')
        assert self._offenders(tmp_path) == []

    def test_an_exemption_does_not_cover_the_rest_of_its_file(self, tmp_path):
        """The bug in the first version: `setup.py` was exempt wholesale, so a
        hardcoded `./quern doctor` anywhere in the file it most protects went
        unnoticed."""
        (tmp_path / "both.py").write_text(
            'value = "./quern"\nadvice = "run ./quern doctor"\n'
        )
        assert self._offenders(tmp_path) == ["both.py:2"]

    def test_every_exemption_is_still_present_in_the_source(self):
        """An exemption whose text no longer appears is a stale licence for a
        string nobody meant to permit."""
        source = "\n".join(
            p.read_text(encoding="utf-8") for p in SERVER.rglob("*.py")
        )
        for needle in (*EXEMPT_EXACT, EXEMPT_CONTAINING):
            assert needle in source, (
                f"exemption {needle!r} matches nothing any more — drop it"
            )


class TestTheWrapperRunsFromAnywhere:
    """The wrapper is shell, and the suite never executed it.

    Reverting it to the previous `exec python3 -m server` fallback passed all
    2490 tests: CI always builds a venv first, so the pre-venv branch is never
    taken there. That branch is exactly the one a tarball user hits, running the
    absolute path `quern_cmd()` now hands them.
    """

    def _install(self, tmp_path):
        """A tarball install: source, wrapper, no venv."""
        import shutil as sh

        root = Path(__file__).resolve().parent.parent
        dest = tmp_path / "share" / "quern"
        dest.mkdir(parents=True)
        sh.copytree(root / "server", dest / "server")
        sh.copy2(root / "quern", dest / "quern")
        (dest / "quern").chmod(0o755)
        assert not (dest / ".venv").exists()
        return dest

    def _run(self, wrapper, cwd, env_extra=None):
        """Run the wrapper from `cwd` and hand back the completed process.

        `--version`, not `setup`. Both tests here ask one question -- does
        `python -m server` resolve *this* wrapper's package -- and that is
        decided in `runpy`, before any subcommand is dispatched. The wrapper
        never branches on its arguments; both `exec` lines forward `"$@"`
        verbatim. And `--version` is dispatched immediately after
        `_maybe_reexec_in_venv`, so it covers the same re-exec path `setup`
        did.

        Why it changed: on a loaded CI runner `setup` exceeded the timeout
        four times on 2026-09-24, across two PRs and three Python versions
        (#303) -- failing for contention rather than for the thing under
        test, and a red matrix on a PR that cannot have caused it sends the
        author to read the wrong diff.

        What `setup` was actually spending that time on is worth recording,
        because the obvious guess is wrong. It was *not* building a venv: the
        fixture copies only `server/` and `quern`, so `_find_project_root()`
        finds no `pyproject.toml` and the venv block is skipped entirely. The
        60 seconds went on its Homebrew, Xcode, pipx and idb probes -- real
        subprocesses against the machine running the suite, which is the
        thing CONTRIBUTING rules out. Removing that is a second reason for
        this change, independent of the flake.

        `--version` over `--help` or `status`: those reach
        `from server.main import cli`, which imports uvicorn, and the fixture
        is a tarball install with no dependencies -- so they crash with
        `ModuleNotFoundError` and the test passes only because both its
        assertions are negative. A probe whose passing state is "crashed
        differently" is one bad assertion away from testing nothing.
        `--version` needs only `from server import get_version` and exits 0,
        which is why `_expect_clean_run` below can assert something positive.

        Verified rather than assumed, on a tarball fixture: with the wrapper
        reverted to `exec python3 -m server "$@"`, `--version` exits 1 with
        `No module named server`; with `-P` stripped, it exits 1 with
        `cannot be directly executed` from a directory containing `server/`.
        Both defects are still caught.
        """
        import os
        import subprocess

        env = dict(os.environ)
        env.pop("PYTHONPATH", None)
        env.update(env_extra or {})
        return subprocess.run(
            [str(wrapper), "--version"], cwd=str(cwd), env=env,
            capture_output=True, text=True, timeout=30,
            input="",  # never let it prompt
        )

    @staticmethod
    def _expect_clean_run(result, what):
        """The wrapper completed and printed our own version line.

        Asserted positively because every other check in this class is the
        *absence* of a string, and a command that fails for some unrelated
        reason satisfies all of them at once -- which is not hypothetical:
        with `--help` here, the fixture's missing dependencies made every run
        exit 1 on `ModuleNotFoundError: uvicorn`, and both tests passed
        regardless.

        What it does not prove: that the output came from quern rather than
        from anything else exiting 0 with that prefix. Measured -- a stub
        wrapper printing "quern 1.0" and never importing the package
        satisfies this. It is a check that the command *ran ours*, not a
        signature. The two absence checks remain the ones with teeth, and
        mutation-testing the wrapper is what proves they bite.
        """
        assert result.returncode == 0, (
            f"{what}: the wrapper exited {result.returncode} rather than "
            f"running\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )
        assert result.stdout.startswith("quern "), (
            f"{what}: expected quern's version line, got {result.stdout!r}"
        )

    def test_it_finds_its_own_package_from_a_foreign_directory(self, tmp_path):
        """The failure this fixes: `-m` searches the caller's cwd, so before
        the fix this was `No module named server`, prefixed with whichever
        python3 was first on PATH — pointing the reader at their interpreter."""
        dest = self._install(tmp_path)
        elsewhere = tmp_path / "elsewhere"
        elsewhere.mkdir()

        result = self._run(dest / "quern", elsewhere)

        self._expect_clean_run(result, "from a foreign directory")
        assert "No module named server" not in (result.stdout + result.stderr), (
            "the wrapper could not import its own package from another "
            f"directory:\n{result.stdout}\n{result.stderr}"
        )

    def test_the_callers_own_server_package_does_not_shadow_ours(self, tmp_path):
        """`-m` puts cwd at sys.path[0], *ahead* of PYTHONPATH — and quern's
        users are by design standing in their own app repositories, where
        `server/` is an ordinary directory name. Without `-P` theirs wins."""
        dest = self._install(tmp_path)
        their_project = tmp_path / "their-app"
        (their_project / "server").mkdir(parents=True)
        (their_project / "server" / "__init__.py").write_text("")
        # A *runnable* shadow, which is the dangerous shape. An empty package
        # loses noisily -- python reports "cannot be directly executed" and
        # any check notices. One with a working __main__ wins silently: it
        # exits 0 and prints whatever the caller's program prints, so a test
        # asserting only that quern did not crash passes against the defect.
        # Verified: with -P removed this prints the marker below and exits 0,
        # which `_expect_clean_run` accepts.
        (their_project / "server" / "__main__.py").write_text(
            'print("quern THEIR-PACKAGE-WON")\n'
        )

        result = self._run(dest / "quern", their_project)

        self._expect_clean_run(result, "from a directory containing server/")
        combined = result.stdout + result.stderr
        assert "THEIR-PACKAGE-WON" not in combined, (
            "the caller's own server/ package shadowed quern's, and did it "
            f"quietly -- their program ran and exited 0:\n{combined}"
        )
        # The noisy shape, kept: an empty or partial shadow fails this way
        # instead, and both are the same defect.
        assert "cannot be directly executed" not in combined, (
            f"the caller's own server/ package shadowed quern's:\n{combined}"
        )
        assert "No module named server" not in combined, combined
